---
driver:
  name: terraform

provisioner:
  name: terraform
      
platforms:
  - name: "aws"

transport:
  name: ssh
  ssh_key: ~/.aws/credentials/key.pem

verifier:
  name: terraform
  format: doc
  groups:
    - name: default
      controls:
        - test_network
      vpcname: ecs_vpc
      
suites:
  - name: default